  1 [custom.sudo]
  2 description = "Display ! when in sudo mode"
  3 command = "echo !"
  4 format = "[$output]($style)"
  5 style = "bold bright-red"
  6 when = "sudo -nv"
  7
  8 [package]
  9 disabled = true
 10
 11 [character]
 12 success_symbol = "[❯](bold purple)"
 13 error_symbol = "[✗](bold red) "
 14
 15 [fill]
 16 symbol = " "
 17
 18 [directory]
 19 truncation_length = 4
 20 format = "[$path]($style)[$lock_symbol]($lock_style) "
 21
 22 [hostname]
 23 ssh_only = false NORMAL  starship.toml[+]                           toml  utf-8[unix]  50% :23/46☰ ℅:14 
"starship.toml" 47L, 975B written
