 [custom.sudo]
 description = "Display ! when in sudo mode"
 command = "echo !"
 format = "[$output]($style)"
 style = "bold bright-red"
 when = "sudo -nv"
 
 [package]
 disabled = true
 
 [character]
 success_symbol = "[❯](bold purple)"
 error_symbol = "[✗](bold red) "
 
 [fill]
 symbol = " "

[directory]
truncation_length = 4
format = "[$path]($style)[$lock_symbol]($lock_style) "

[hostname]
ssh_only = false NORMAL  starship.toml[+]                           toml  utf-8[unix]  50% :23/46☰ ℅:14 
"starship.toml" 47L, 975B written
